Repository AY2425S2-CS2103-F08-2/tp, pull requests merged in 2025-03, with the labels that each got.

#7 Add profile photo for Ervin
  docs/images/makisekurisux.png
Labels: type.Task

#8 Add profile photo for jovin
  docs/images/jovin-ang.png
Labels: type.Task

#12 Add profile picture into images folder
  docs/images/johngao122.png
Labels: type.Task

#13 Add Yu Yang's Photo
  docs/images/yuyang.jpg
Labels: type.Task

#15 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#17 Update AboutUs.md with Jovin's profile details
  docs/AboutUs.md
Labels: type.Task

#21 Revert "Branch update about us"
  docs/AboutUs.md
Labels: type.Bug

#19 Update About Us Page
  docs/AboutUs.md
Labels: type.Task

#24 Update Yu Yang's Photo
  docs/images/yuyang.png
Labels: type.Task

#25 Update Yu Yang's Photo
  docs/images/yuyang011.png
Labels: type.Task

#26 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#31 Update README page to match the project
  README.md
Labels: type.Task

#23 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#3 Update Gradle and project dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: type.Task, priority.Medium

#30 Branch website update
  .gitignore
  docs/_markbind/layouts/default.md
  docs/images/Ui.png
  docs/index.md
  docs/package-lock.json
  docs/package.json
Labels: type.Task

#35 Update profile picture
  docs/images/jovin-ang.png
Labels: type.Task

#33 Add policy number field
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PolicyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#65 Create TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Medium

#70 Add Renewal date command and UI and integrated renewaldate into policy
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewRenewalsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ViewRenewalsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RenewalProcessor.java
  src/main/java/seedu/address/model/RenewalTableData.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RenewalTableConfig.java
  src/main/java/seedu/address/ui/RenewalsTable.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RenewalsTable.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewRenewalsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewRenewalsCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/RenewalProcessorTest.java
  src/test/java/seedu/address/model/RenewalTableDataTest.java
  src/test/java/seedu/address/model/person/PolicyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: priority.High

#80 Renewal date class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/RenewalProcessor.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/model/person/RenewalDate.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/RenewalTableConfig.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ViewRenewalsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/RenewalProcessorTest.java
  src/test/java/seedu/address/model/person/PolicyTest.java
  src/test/java/seedu/address/model/person/RenewalDateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#87 Add support for address searching in find command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindPersonsPredicateTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/FindPersonsPredicateBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, priority.Medium

#91 Update codecov configuration
  .codecov.yml
Labels: type.Task

#74 Create FilterByDateCommandParser and FilterByDateCommand
  src/main/java/seedu/address/logic/commands/FilterDateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterDateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Policy.java
  src/test/java/seedu/address/logic/commands/FilterDateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterDateCommandParserTest.java
Labels: priority.High

#81 Add Fields to Status Bar
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Enhancement, priority.Medium

#99 Rename output JAR file to 'InsureBook.jar'
  build.gradle
Labels: type.Task, priority.High

#115 Add sorting functionality to FindCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewRenewalsCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, type.Bug, priority.Medium, severity.VeryLow

#119 Update ModelClassDiagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Task

#111 add policy type to Policy class
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/RenewalProcessor.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/model/person/PolicyType.java
  src/main/java/seedu/address/model/person/PolicyTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailPanel.java
  src/main/java/seedu/address/ui/RenewalTableConfig.java
  src/main/java/seedu/address/ui/RenewalsTable.fxml
  src/main/java/seedu/address/ui/RenewalsTable.java
  src/main/resources/view/PersonDetailPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPersonsPredicateTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PolicyTest.java
  src/test/java/seedu/address/model/person/PolicyTypeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PolicyTypeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/FindPersonsPredicateBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium
