Repository AY2425S2-CS2103-F08-2/tp, pull requests merged in 2025-04, with the labels that each got.

#137 Add Notes to Client Profile
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RenewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonDetailPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailPanel.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/missingLastUpdatedAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#153 Fix Sample Data Util mismatch with renewaldate format
  build.gradle
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, alpha-bug

#138 Update docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindPersonPredicateClassDiagram.puml
  docs/diagrams/FindPersonPredicateSequenceDiagram.puml
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#161 Improve layout for FindPersonsPredicate class diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindPersonPredicateClassDiagram.puml
Labels: type.Task

#163 Update to Fix Bugs
  docs/UserGuide.md
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: alpha-bug

#175 Fix Data Persistence Bugs
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetailPanel.java
  src/main/java/seedu/address/ui/RenewalsTable.java
Labels: priority.High, alpha-bug

#171 Update User and Dev Guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterDateCommandClassDiagram.puml
  docs/diagrams/FilterDateCommandSequenceDiagram.puml
Labels: type.Bug, severity.High, alpha-bug

#262 Bug fixes for filter command
  src/main/java/seedu/address/logic/commands/FilterDateCommand.java
  src/main/java/seedu/address/logic/parser/FilterDateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Policy.java
  src/main/java/seedu/address/model/person/RenewalDate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterDateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterDateCommandParserTest.java
Labels: type.Bug, severity.Low

#222 Fix markdown rendering on info box
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#267 Find command bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/PolicyTypeContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PolicyTypeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/FindPersonsPredicateBuilder.java
Labels: type.Bug, severity.Medium, bug-findeditadd

#281 Bugs in filter command v1.5
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FilterDateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/parser/FilterDateCommandParserTest.java
Labels: type.Bug, bug-filter
